version: '3'
services:
  api:
    build: ./api
    container_name: api
    volumes:
      - shared-volume: /shared
    expose:
      - 8000

  gcc:
    image: gcc
    container_name: gcc-runtime
    depends_on:
      - api
    volumes:
      - shared-volume: /shared

  python:
    image: python:alpine
    container_name: python-runtime
    depends_on:
      - api
    volumes:
      - shared-volume: /shared

  node:
    image: node:18-alpine
    container_name: node-runtime
    depends_on:
      - api
    volumes:
      - shared-volume: /shared

volumes: 
  shared-volume:
